site_name: AILAB - HealthTech
repo_url: https://github.com/Diogo-Olivv/HealthTech.git

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - search.suggest

plugins:
  - search
  - awesome-pages
