site_name: HealthTech
repo_url: https://github.com/Diogo-Olivv/HealthTech.git

theme:
  name: material
  logo: assets/logo/Icon.svg
  favicon: assets/logo/favicon.ico
  font:
    text: Inter
    code: Roboto Mono
  palette:
    - scheme: default
      primary: custom
      accent: custom
  features:
    - navigation.tabs
    - navigation.indexes
    - search.suggest

extra_css:
  - assets/stylesheets/extra.css

plugins:
  - search
  - awesome-pages
