name: Deploy MkDocs

on:
  push:
    branches:
      - main
      - docs

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurar Identidade do Git
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Instalar MkDocs e Tema Material
        run: |
          pip install mkdocs-material
          pip install mkdocs-awesome-pages-plugin

      - name: Deploy para o GitHub Pages
        run: mkdocs gh-deploy --force
